=== ganesh290105/xml-file/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  This is the XML Schema (XSD) for the bookstore.
  It defines the structure and rules for the 'bookstore.xml' file.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Definition for the root element: <bookstore> -->
  <xs:element name="bookstore">
    <xs:complexType>
      <xs:sequence>
        <!-- The <bookstore> element can contain one or more <book> elements -->
        <xs:element name="book" maxOccurs="unbounded" minOccurs="1" type="BookType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Definition for the <book> element and its children -->
  <xs:complexType name="BookType">
    <xs:sequence>
      <!-- Defines the child elements that must appear within a <book> element -->
      <xs:element name="title" type="xs:string"/>
      <xs:element name="author" type="xs:string"/>
      <xs:element name="genre" type="GenreType"/>
      <xs:element name="price" type="xs:decimal"/>
    </xs:sequence>
    <!-- Defines the 'id' attribute for the <book> element -->
    <xs:attribute name="id" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Definition for the <genre> element's allowed values -->
  <xs:simpleType name="GenreType">
    <xs:restriction base="xs:string">
      <!-- Restricts the genre to one of the following values -->
      <xs:enumeration value="Fiction"/>
      <xs:enumeration value="Non-Fiction"/>
      <xs:enumeration value="Science Fiction"/>
      <xs:enumeration value="Fantasy"/>
      <xs:enumeration value="Mystery"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== ganesh290105/xml-file/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bookstore.xsl"?>
<!-- 
  This is the XML document containing the list of books.
  It is linked to the 'bookstore.xsd' schema for validation.
  The 'xsi:noNamespaceSchemaLocation' attribute points to the XSD file.
-->
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="bookstore.xsd">
  
  <book id="bk101">
    <title>Chhava</title>
    <author>Shivaji Sawant</author>
    <genre>Fiction</genre>
    <price>120</price>
  </book>
  
  <book id="bk102">
    <title>Malgudi Daays</title>
    <author>R.k.Narayan</author>
    <genre>Fiction</genre>
    <price>200</price>
  </book>
  
  <book id="bk103">
    <title>Ramayana</title>
    <author>Rushi Walmiki</author>
    <genre>Non-Fiction</genre>
    <price>283</price>
  </book>
  
  <book id="bk104">
    <title>A Brief History of Time</title>
    <author>Stephen Hawking</author>
    <genre>Non-Fiction</genre>
    <price>180</price>
  </book>
  
  <book id="bk105">
    <title>The Lord of the Rings</title>
    <author>J.R.R. Tolkien</author>
    <genre>Fantasy</genre>
    <price>200</price>
  </book>

</bookstore>
